### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by 4nte** [VolantMQ/helm#1]
This is a list of TODO's required before the chart can be considered generally available and ready for production use.

- [x] Prometheus Operator integration
- [x] Persistence (PVC)
- [x] Liveness & Readiness probes
- [x] Chart tests
- [x] NOTES.txt (a meaningful post-install message)
- [x] README
  - [x] Installation
  - [x] Chart values
- [x] Ingress
- [x] License Apache-2.0

If you think something is missing from the roadmap, please let me know!

**Comment by saikatharryc** [comment]
@4nte I believe we need to add support for ingress as well?

**Comment by 4nte** [comment]
> @4nte I believe we need to add support for ingress as well?

That's true, I just added ingress to the roadmap.

**Comment by saikatharryc** [comment]
@4nte  Are we planning to support helm2 as well?

**Comment by 4nte** [comment]
> @4nte Are we planning to support helm2 as well?

I initially planned for helm3, however, it would be great to make it v2 compatible too.

Also I haven't tested with Helm2 and assumed that it would work fine, are you aware of something in the current chart that is not compatible with v2?

**Comment by saikatharryc** [comment]
I'm also not sure about that, but in the test, I have added one hook [here](https://github.com/VolantMQ/helm/commit/3f7befd5f6081ee5c8f94227b9d4e26eadaa37a7#diff-8c12336d55f4583491692e6af216a7b7R16). 
```
helm.sh/hook-delete-policy: hook-succeeded
```
which might not work with v2.

**Comment by 4nte** [comment]
I've opened #7 to track Helm2 compatibility issues. I suggest we first finish everything with focus on v3 and later worry about v2, ofcourse, unless someone wants to jump in and resolve this immediately.

**Comment by troian** [comment]
Added License to Roadmap

**Comment by troian** [comment]
@4nte added license

**Comment by saikatharryc** [comment]
removing contribution from this list as of now. and closing as the rest of the items is completed.
